[package]
name = "todos"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
leptos = { version = "0.6.13", features = ["csr", "nightly"] }
log = "0.4.22"

[dev-dependencies]
wasm-bindgen = "0.2.92"
